---

- name: reload etcd systemd
  become: true
  systemd:
    daemon_reload: true
  when: groups['etcd'] is defined and inventory_hostname in groups['etcd']

- name: restart etcd
  become: true
  service:
    name: etcd
    enabled: true
    state: restarted
  when: groups['etcd'] is defined and inventory_hostname in groups['etcd']
