---

- name: test/nginx-deployment | apply config
  become: true
  run_once: true
  kubernetes.core.k8s:
    apply: true
    server_side_apply: {field_manager: ansible-playbook}
    template: templates/nginx-deployment.yml.j2

- name: test/pyechoserver-deployment | apply config
  become: true
  run_once: true
  kubernetes.core.k8s:
    apply: true
    server_side_apply: {field_manager: ansible-playbook}
    template: templates/pyechoserver-deployment.yml.j2

- name: test/tcpecho-deployment | apply config
  become: true
  run_once: true
  kubernetes.core.k8s:
    apply: true
    server_side_apply: {field_manager: ansible-playbook}
    template: templates/tcpecho-deployment.yml.j2
