---

- name: reload node systemd
  become: true
  systemd:
    daemon_reload: true
  throttle: 1

- name: restart containerd
  become: true
  service:
    name: containerd
    enabled: true
    state: restarted
  throttle: 1

- name: restart kubelet
  become: true
  service:
    name:   kubelet
    enabled: true
    state: restarted
  throttle: 1

- name: restart kube-proxy
  become: true
  service:
    name: kube-proxy
    enabled: true
    state: restarted
  throttle: 1
