---

- name: reload controller systemd
  become: true
  systemd:
    daemon_reload: true
  throttle: 1

- name: restart kube-apiserver
  become: true
  service:
    name:   kube-apiserver
    enabled: true
    state: restarted
  throttle: 1

- name: restart kube-controller-manager
  become: true
  service:
    name: kube-controller-manager
    enabled: true
    state: restarted
  throttle: 1

- name: restart kube-scheduler
  become: true
  service:
    name: kube-scheduler
    enabled: true
    state: restarted
  throttle: 1

- name: restart keepalived
  become: true
  service:
    name: keepalived
    enabled: true
    state: restarted
