---

- assert: { that: "apiserver.url is defined and apiserver.url is truthy", fail_msg: "Please define apiserver.url" }

- name: apiserver-lb-awsalb | Create apiserver certificate/ key
  include_tasks: sslcerts-apiserver.yml

- name: apiserver-lb-awsalb | Create regional ALBs and DNS
  vars:
    _aws_controller_regions: "{{ cluster_vars[buildenv].hosttype_vars.controller.region_vars.keys() | list }}"
  block:
    - name: apiserver-lb-awsalb | ec2_instance_info
      ec2_instance_info:
        filters:
          "tag:cv__hosttype": "controller"
          "tag:cv__cluster_name": "{{ cluster_name }}"
          "instance-state-name": ["running"]
        access_key: "{{ cluster_vars[buildenv].aws_access_key | default(omit) }}"
        secret_key: "{{ cluster_vars[buildenv].aws_secret_key | default(omit) }}"
        session_token: "{{ cluster_vars[buildenv].aws_session_token | default(omit) }}"
        region: "{{ item }}"
      loop: "{{ _aws_controller_regions }}"
      loop_control: { label: "{{ item }}" }
      delegate_to: localhost
      run_once: true
      register: r__ec2_instance_info

    - name: apiserver-lb-awsalb | r__ec2_instance_info
      debug: msg="{{ r__ec2_instance_info }}"
      run_once: true

    - name: apiserver-lb-awsalb | controller instances by region
      set_fact:
        _aws_controller_instances_by_region: "{{ r__ec2_instance_info.results | json_query('[?instances && length(instances)>`0`].{region: item, instances: instances, vpc_id: instances[0].vpc_id, subnet_ids: instances[].subnet_id}') }}"
      run_once: true

    - name: apiserver-lb-awsalb | create elb_target_group
      elb_target_group:
        access_key: "{{ cluster_vars[buildenv].aws_access_key | default(omit) }}"
        secret_key: "{{ cluster_vars[buildenv].aws_secret_key | default(omit) }}"
        session_token: "{{ cluster_vars[buildenv].aws_session_token | default(omit) }}"
        region: "{{ item.region }}"
        name: "{{ cluster_name }}-apiserver"
        protocol: https
        port: "{{ apiserver.secure_port }}"
        vpc_id: "{{ item.vpc_id }}"
        health_check_protocol: https
        health_check_path: /livez
        successful_response_codes: "200"
        targets: "{{ item.instances | json_query(\"[].{Id: instance_id, Port: `\" + apiserver.secure_port|string + \"`}\") }}"
        state: present
      loop: "{{ _aws_controller_instances_by_region }}"
      loop_control: { label: "{{ item.region }}" }
      delegate_to: localhost
      run_once: true
      register: r__elb_target_group

    - name: apiserver-lb-awsalb | r__elb_target_group
      debug: msg="{{ r__elb_target_group }}"
      run_once: true

    - name: apiserver-lb-awsalb | upload a self-signed certificate
      community.aws.aws_acm:
        access_key: "{{ cluster_vars[buildenv].aws_access_key | default(omit) }}"
        secret_key: "{{ cluster_vars[buildenv].aws_secret_key | default(omit) }}"
        session_token: "{{ cluster_vars[buildenv].aws_session_token | default(omit) }}"
        region: "{{ item.region }}"
        certificate: "{{ k8s_certs['apiserver-crt.pem'] }}"
        private_key: "{{ k8s_certs['apiserver-key.pem'] }}"
        certificate_chain: "{{ ssl_ca['ca-crt.pem'] }}"
        name_tag: "{{ cluster_name }}-apiserver"
      loop: "{{ _aws_controller_instances_by_region }}"
      loop_control: { label: "{{ item.region }}" }
      delegate_to: localhost
      run_once: true
      register: r__aws_acm

    - name: apiserver-lb-awsalb | Create an ALB and attach the listeners
      elb_application_lb:
        access_key: "{{ cluster_vars[buildenv].aws_access_key | default(omit) }}"
        secret_key: "{{ cluster_vars[buildenv].aws_secret_key | default(omit) }}"
        session_token: "{{ cluster_vars[buildenv].aws_session_token | default(omit) }}"
        region: "{{ item.region }}"
        name: "{{ cluster_name }}-apiserver"
        security_groups: "{{ item.instances | json_query('[].security_groups[].group_id') | unique }}"
        subnets: "{{ item.subnet_ids | unique }}"
        scheme: internal
        listeners:
          - Protocol: HTTPS
            Port: "{{ apiserver.secure_port }}"
            SslPolicy: ELBSecurityPolicy-2016-08
            Certificates:
              - CertificateArn: "{{ _acm.certificate.arn }}"
            DefaultActions: [{ Type: forward, TargetGroupName: "{{ _tg.target_group_name }}" }]
      vars:
        _acm: "{{ r__aws_acm.results | json_query(\"[?item.region=='\" + item.region + \"'] | [0]\") }}"
        _tg: "{{ r__elb_target_group.results | json_query(\"[?item.region=='\" + item.region + \"'] | [0]\") }}"
      loop: "{{ _aws_controller_instances_by_region }}"
      loop_control: { label: "{{ item.region }}" }
      delegate_to: localhost
      run_once: true
      register: r__elb_application_lb

    - name: apiserver-lb-awsalb | r__elb_application_lb
      debug: msg="{{ r__elb_application_lb }}"
      run_once: true

    - name: apiserver-lb-awsalb | create CNAME
      route53:
        access_key: "{{ cluster_vars[buildenv].aws_access_key | default(omit) }}"
        secret_key: "{{ cluster_vars[buildenv].aws_secret_key | default(omit) }}"
        session_token: "{{ cluster_vars[buildenv].aws_session_token | default(omit) }}"
        state: present
        zone: "{{ cluster_vars.dns_nameserver_zone }}"
        record: "{{ apiserver.url | urlsplit('hostname') }}"
        type: CNAME
        ttl: 30
        value: "{{ item.dns_name }}"
        identifier: "{{ item.item.region if (r__elb_application_lb.results | length > 1) else omit }}"
        region: "{{ item.item.region if (r__elb_application_lb.results | length > 1) else omit }}"
        private_zone: "{{ cluster_vars.route53_private_zone | default(true) }}"
        overwrite: true
      loop: "{{ r__elb_application_lb.results }}"
      loop_control: { label: "{{ item.item.region }}" }
      become: false
      delegate_to: localhost
      run_once: true
      when: cluster_vars.dns_server == "route53"
