---

- name: apiserver-lb-ha-keepalived | Allow apps to bind on non-local addresses (net.ipv4.ip_nonlocal_bind=1)
  become: true
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: apiserver-lb-ha-keepalived | Accept packets with local source addresses (net.ipv4.conf.eth0.accept_local=1)
  become: true
  sysctl:
    name: "net.ipv4.conf.{{ansible_facts.default_ipv4.interface}}.accept_local"
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: apiserver-lb-ha-keepalived | Install keepalived package (debian)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: ['keepalived']
    state: present
  notify: ["restart keepalived"]
  when: ansible_facts['os_family'] == 'Debian'

- name: apiserver-lb-ha-keepalived | Install keepalived package (redhat)
  become: true
  ansible.builtin.dnf:
    name: ['keepalived']
  when: ansible_facts['os_family'] == 'RedHat'

- name: apiserver-lb-ha-keepalived | Install keepalived-bypass-ipvs.sh
  become: true
  template: src=keepalived-bypass-ipvs.sh.j2 dest=/etc/keepalived/keepalived-bypass-ipvs.sh owner=root group=root mode=0755
  notify: ["restart keepalived"]

- name: apiserver-lb-ha-keepalived | Create /run/keepalived directory, so keepalived can create the FIFO.  Created via tmpfiles.d -  can't use the 'ansible.builtin.file' module because /run is a tmpfs-backed path, which is wiped on reboot (so a reboot would mean no fifo for keepalived)
  become: true
  block:
    - name: apiserver-lb-ha-keepalived | Create keepalived tmpfiles.d config
      copy:
        dest: /etc/tmpfiles.d/keepalived.conf
        content: |
          d /run/keepalived 0755 root root -
        owner: root
        group: root
        mode: '0644'

    - name: apiserver-lb-ha-keepalived | Apply tmpfiles.d immediately
      command: systemd-tmpfiles --create /etc/tmpfiles.d/keepalived.conf

- name: apiserver-lb-ha-keepalived | Configure keepalived - create /etc/keepalived/keepalived.conf
  become: true
  template:
    src: keepalived-lb-apiserver.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    apiserver_keepalived_real_servers: "{{ groups['controller'] | map('extract', hostvars, ['ansible_facts', 'default_ipv4', 'address']) | sort }}"
    apiserver_keepalived_peers: "{{ groups['controller'] | map('extract', hostvars, ['ansible_facts', 'default_ipv4', 'address']) | difference([ansible_host]) | sort }}"
  notify: ["restart keepalived"]

- name: apiserver-lb-ha-keepalived | Configure keepalived logging (debian)
  become: true
  lineinfile:
    dest: "/etc/default/keepalived"
    regexp: '^DAEMON_ARGS="(.*")'
    line: 'DAEMON_ARGS="--log-detail \1'
    backrefs: true
  notify: ["restart keepalived"]
  when: ansible_facts['os_family'] == 'Debian'

- name: apiserver-lb-ha-keepalived | Configure keepalived logging (redhat)
  become: true
  lineinfile:
    dest: "/etc/sysconfig/keepalived"
    regexp: '^KEEPALIVED_OPTIONS="(.*")'
    line: 'KEEPALIVED_OPTIONS="--log-detail \1'
    backrefs: true
  notify: ["restart keepalived"]
  when: ansible_facts['os_family'] == 'RedHat'

- name: apiserver-lb-ha-keepalived | flush handlers
  meta: flush_handlers
