---

- name: apiserver-lb-ha-keepalived | Allow apps to bind on non-local addresses (net.ipv4.ip_nonlocal_bind=1)
  become: true
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: apiserver-lb-ha-keepalived | Accept packets with local source addresses (net.ipv4.conf.eth0.accept_local=1)
  become: true
  sysctl:
    name: "net.ipv4.conf.{{ansible_facts.default_ipv4.interface}}.accept_local"
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: apiserver-lb-ha-keepalived | Create /etc/keepalived directory
  become: true
  file:
    path: /etc/keepalived
    state: directory
    mode: 0755

- name: apiserver-lb-ha-keepalived | copy keepalived-bypass-ipvs.service
  become: true
  template: src=keepalived-bypass-ipvs.service.j2 dest=/etc/systemd/system/keepalived-bypass-ipvs.service
  notify: ["reload controller systemd", "restart keepalived-bypass-ipvs"]

- name: apiserver-lb-ha-keepalived | copy keepalived-bypass-ipvs.sh
  become: true
  template: src=keepalived-bypass-ipvs.sh.j2 dest=/etc/keepalived/keepalived-bypass-ipvs.sh owner=root group=root mode=0755
  notify: ["restart keepalived-bypass-ipvs"]

- name: apiserver-lb-ha-keepalived | flush handlers
  meta: flush_handlers

- name: apiserver-lb-ha-keepalived | Install keepalived package
  become: true
  apt:
    update_cache: true
    name: ['keepalived']
    state: present
  notify: ["restart keepalived"]

- name: apiserver-lb-ha-keepalived | Configure keepalived
  become: true
  template:
    src: keepalived-lb-apiserver.conf.j2
    dest: /etc/keepalived/keepalived.conf
  vars:
    apiserver_keepalived_real_servers: "{{ groups['controller'] | map('extract', hostvars, ['ansible_facts', 'default_ipv4', 'address']) | sort }}"
    apiserver_keepalived_peers: "{{ groups['controller'] | map('extract', hostvars, ['ansible_facts', 'default_ipv4', 'address']) | difference(ansible_host) | sort }}"
  notify: ["restart keepalived"]

- name: apiserver-lb-ha-keepalived | Configure keepalived logging
  become: true
  lineinfile:
    dest: "/etc/default/keepalived"
    regexp: '^DAEMON_ARGS="(.*")'
    line: 'DAEMON_ARGS="--log-detail \1'
    backrefs: true
  notify: ["restart keepalived"]

- name: apiserver-lb-ha-keepalived | flush handlers
  meta: flush_handlers
