---

- name: os_cfg_debian | apt install python3-debian on localhost
  become: true
  ansible.builtin.apt:
    name: ['python3-debian']
    update_cache: true

- name: os_cfg_debian | Add Repository and key (using new method, supported in > Ubuntu20.04, required by Ubuntu24.04.1)
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    architectures: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' if ansible_facts['architecture'] == 'aarch64' else ansible_facts['architecture'] }}"
    uris: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version | regex_replace('^(\\d+\\.\\d+).*', '\\1') }}/deb/"
    suites: "/"
    signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version | regex_replace('^(\\d+\\.\\d+).*', '\\1') }}/deb/Release.key"
    state: present

- name: os_cfg_debian | apt install kubectl on localhost
  become: true
  ansible.builtin.apt:
    name: ['build-essential', 'kubectl', 'ncat', 'google-cloud-sdk']
    update_cache: true

- name: os_cfg_debian | Install PIP packages
  become: true
  ansible.builtin.pip:
    name: ["openshift", "kubernetes-validate"]
    break_system_packages: true
