---

- name: Add Google's apt key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Adding google cloud sdk repository
  become: true
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' if ansible_facts['architecture'] == 'aarch64' else ansible_facts['architecture'] }}] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present

- name: apt install on localhost
  become: true
  ansible.builtin.apt:
    name: ['build-essential', 'kubectl', 'ncat', 'google-cloud-sdk']
    update_cache: True

- name: Install PIP packages
  become: true
  ansible.builtin.pip:
    name: ["openshift", "kubernetes-validate"]
    break_system_packages: true
