---

- name: common | write out hosts to /etc/hosts when no DNS in use
  become: true
  blockinfile:
    dest: "/etc/hosts"
    block: "{{ hostvars | json_query(\"*.join(' ', [ansible_facts.default_ipv4.address, ansible_facts.hostname])\") | sort | join('\n') }}"
    state: present
    create: true
    marker: "# ansible k8s inventory hosts {mark}"
    prepend_newline: true
  when: (cluster_vars.dns_server is not defined  or  cluster_vars.dns_server == '')  or  (cluster_vars.dns_domain is not defined  or  cluster_vars.dns_domain == "")

- name: common | Allow ip_forward (net.ipv4.ip_forward=1)
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: "common | Enable bridge netfilter manually when a bridging CNI is used (https://github.com/kubernetes/kubernetes/issues/24018)"
  block:
    - name: apiserver-lb-ha-keepalived | Install iptables (also installs br_netfilter (redhat)
      become: true
      ansible.builtin.dnf:
        name: [ 'iptables' ]
      when: ansible_facts['os_family'] == 'RedHat'

    - name: common | load the br-netfilter module and make it persistent
      become: true
      modprobe:
        name: "{{ item }}"
        state: present
        persistent: present
      with_items:
        - "overlay"
        - "br_netfilter"

    - name: common | set net.bridge.bridge-nf-call-ip[6]tables=1
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_set: true
        state: present
        reload: true
      with_items:
        - "net.bridge.bridge-nf-call-iptables"
        - "net.bridge.bridge-nf-call-ip6tables"
  when: flannel_version is defined  and  flannel_version != ""