---

- name: node/hostconfig
  block:
    - name: node/hostconfig | Disable swap for current session
      become: true
      command: swapoff -a

    - name: node/hostconfig | Remove swapfile from /etc/fstab
      become: true
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items: ["swap", "none"]

    - name: node/hostconfig | install unzip, for ansible.builtin.unarchive (debian)
      become: true
      ansible.builtin.apt:
        name: ['unzip']
        update_cache: True
      when: ansible_facts['os_family'] == 'Debian'

    - name: node/hostconfig | install unzip, for ansible.builtin.unarchive (redhat)
      become: true
      ansible.builtin.dnf:
        name: ['unzip', 'tar']
      when: ansible_facts['os_family'] == 'RedHat'

    - name: node/hostconfig | install python3-cryptography (redhat)
      become: true
      ansible.builtin.dnf:
        name: ['python3-cryptography']
      when: ansible_facts['os_family'] == 'RedHat'


- name: node | Run cloud-specific VIP config (if defined)
  include_tasks: "{{item}}"
  with_first_found: [{ files: ["vips_{{cluster_vars.cloud_type}}.yml"], skip: true }]

- name: node | install node-dependent packages (debian)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: ['conntrack', 'ipset']
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: node | install node-dependent packages (rhel)
  become: true
  ansible.builtin.dnf:
    name: ['conntrack', 'ipset']
  when: ansible_facts['os_family'] == 'RedHat'

- name: node | load the nf_conntrack module
  become: true
  modprobe:
    name: nf_conntrack
    state: present

- name: node | install container runtime
  include_tasks: config-containerd.yml

- name: node | install and configure kubelet
  include_tasks: config-kubelet.yml

- name: node | install container kube-proxy
  include_tasks: config-kube-proxy.yml

- name: node | flush handlers
  meta: flush_handlers

- name: node | debug ansible_play_batch
  debug: msg="{{ansible_play_batch}}"

- name: node | Wait for nodes to be created (NOT necessarily 'Ready')
  become: true
  delegate_to: "{{groups['controller'][0]}}"
  uri:
    url: "{% if apiserver.url is defined and apiserver.url is truthy %}{{ apiserver.url }}{% elif apiserver.keepalived.vip_cidr is defined and apiserver.keepalived.vip_cidr is truthy %}https://{{apiserver.keepalived.vip_cidr | ansible.utils.ipaddr('address')}}{% endif %}:{{apiserver.secure_port}}/api/v1/nodes/"
    method: GET
    status_code: 200
    validate_certs: false
    ca_path: "{{k8s_home_kube_dir}}/{{cluster_name}}/ca-crt.pem"
    client_cert: "{{k8s_home_kube_dir}}/{{cluster_name}}/admin-crt.pem"
    client_key: "{{k8s_home_kube_dir}}/{{cluster_name}}/admin-key.pem"
    return_content: true
  run_once: true
  register: r__clusternodes_result
  until: >
    r__clusternodes_result.status == 200  and
    'json' in r__clusternodes_result  and
    (r__clusternodes_result.json['items'] | json_query("[].metadata.name") | symmetric_difference(ansible_play_batch) | length == 0)
  retries: 10     # retries: 60 = 5 minutes
  delay: 5

- name: node | nodes status
  debug:
    msg: "{{r__clusternodes_result}}"
  run_once: true

- name: node/worker | label all nodes with 'node' role
  become: true
  delegate_to: "{{groups['controller'][0]}}"
  kubernetes.core.k8s:
    state: patched
    kind: Node
    name: "{{ansible_facts['hostname']}}"
    resource_definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ansible_facts['hostname']}}"
        labels:
          node-role.kubernetes.io/node: 'true'
          topology.kubernetes.io/zone: "{{hostvars[ansible_facts['hostname']].regionzone}}"

- name: node/edge | label and taint node-edge nodes with 'edge_ingress.node_role_name' role
  become: true
  delegate_to: "{{groups['controller'][0]}}"
  kubernetes.core.k8s:
    apply: true
    server_side_apply: {field_manager: ansible-playbook}
    resource_definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ansible_facts['hostname']}}"
        labels: "{{ { 'node-role.kubernetes.io/' + edge_ingress.node_role_name: 'true' } }}"
      spec:
        taints:
          - key: "node-role.kubernetes.io/{{edge_ingress.node_role_name}}"
            value: "true"
            effect: NoExecute
  when: groups['node-edge'] is defined and inventory_hostname in groups['node-edge']

